# ---- PATHS ----
dataset_raw: "data/CASIA-B-raw"
dataset_preprocessed: "data/CASIA-B-preprocessed"
work_dir: "runs/checkpoints"
plots_dir: "runs/plots"

# ---- DATASET ----
resolution: 64
dataset: "CASIA-B"
pid_num: 73
pid_shuffle: false

# ---- MODEL ----
hidden_dim: 256
lr: 0.0001
batch_P: 8
batch_K: 16
margin: 0.2
frame_num: 30
total_iter: 10000
save_iter: 1000
plot_iter: 1000
num_workers: 1
model_name: "GaitGL"
hard_or_full_trip: "hard"
restore_iter: 0
save_name: "GaitGL"
train_pid_num: 73

# ---- INFERENCE ----
img_size: 112
checkpoint: "runs/checkpoints/encoder.ptm"
