# ---- PATHS ----
dataset_raw: "data/CASIA-B-raw"
dataset_preprocessed: "data/CASIA-B-preprocessed"
work_dir: "runs/checkpoints"
plots_dir: "runs/plots"

# ---- DATASET ----
resolution: 64
dataset: "CASIA-B"
pid_num: 73
pid_shuffle: false

# ---- MODEL ----
hidden_dim: 256
lr: 0.0001
batch_P: 8
batch_K: 16
margin: 0.2
frame_num: 30
total_iter: 80000
num_workers: 2
model_name: "GaitGL"

# ---- INFERENCE ----
img_size: 112
checkpoint: "runs/checkpoints/encoder.ptm"
